name : Postman Collection Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron : 30 02 * * * 
    - cron : 00 14 * * * 
    - cron : 00 06 * * 1-5

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: checkout the code
        uses: actions/checkout@v5.0.0

      - name: Install node.js and npm
        uses: actions/setup-node@v3.9.1
        with: 
          node-version: '22'

      - name: Install Newman and html globally
        run : |
              npm install -g newman
              npm install -g newman-reporter-html
              npm install -g newman-reporter-htmlextra

      - name: Run the Postman Collection with newman
        run: |
             newman run 'Inwarranty-flow Collection.postman_collection.json' \
             -e QA.postman_environment.json \
             -d testData.csv \
             -r cli,html

      - name: Newman Report
        if: always() # ensure that the archive executed irrespective whether the previous step has passed or not
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Newman Report
          path: newman/*.html
             
              
        
       

    
    
